-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "20")

-- Settings
hl.config({
    ecosystem = {
        no_donation_nag = true,
    },
    general = {
        resize_on_border = false,
    },
    misc = {
        disable_splash_rendering = true,
    },
})

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "1366x0",
    scale = 0.5,
    cm = "srgb",
    mirror = 0,
})
